name: Java CI with SonarQube and GlassFish Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test


      - name: Download GlassFish
        run: |
          wget http://download.oracle.com/glassfish/4.1/release/glassfish-4.1.zip
          unzip glassfish-4.1.zip -d /opt
          chmod +x /opt/glassfish4/bin/asadmin

      - name: Deploy WAR to GlassFish
        env:
          GLASSFISH_ADMIN_PASSWORD: ${{ secrets.GLASSFISH_ADMIN_PASSWORD }}
          GLASSFISH_ADMIN_USERNAME: ${{ secrets.GLASSFISH_ADMIN_USERNAME }}
          GLASSFISH_HOST: ${{ secrets.GLASSFISH_HOST }}
          GLASSFISH_PORT: ${{ secrets.GLASSFISH_PORT }}
        run: |
          echo "AS_ADMIN_PASSWORD=${GLASSFISH_ADMIN_PASSWORD}" > glassfish-password.txt
          chmod 600 glassfish-password.txt
          /opt/glassfish4/bin/asadmin --host $GLASSFISH_HOST \
            --port $GLASSFISH_PORT \
            --user $GLASSFISH_ADMIN_USERNAME \
            --passwordfile ./glassfish-password.txt \
            deploy --force target/*.war
